apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: connect-controller-milo-discovery
rules:
- apiGroups:
  - resourcemanager.miloapis.com
  resources:
  - projects
  - projectcontrolplanes
  verbs: ["get", "list", "watch"]
