---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: connect-manager
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - secrets
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - compute.datumapis.com
  resources:
  - workloads
  verbs:
  - create
  - delete
  - get
  - patch
  - update
- apiGroups:
  - connect.datumapis.com
  resources:
  - connectgatewayclasses
  - connectgateways
  - connectnetworkbindings
  - connectoradvertisements
  - connectorclasses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - connect.datumapis.com
  resources:
  - connectgatewayclasses/status
  - connectgateways/status
  - connectnetworkbindings/status
  - connectoradvertisements/status
  - connectorclasses/status
  - connectors/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - connect.datumapis.com
  resources:
  - connectors
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - connect.datumapis.com
  resources:
  - connectors/finalizers
  verbs:
  - update
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - iam.miloapis.com
  resources:
  - policybindings
  verbs:
  - create
  - delete
  - get
- apiGroups:
  - iam.miloapis.com
  resources:
  - serviceaccounts
  verbs:
  - create
  - delete
  - get
  - patch
  - update
- apiGroups:
  - identity.miloapis.com
  resources:
  - serviceaccountkeys
  verbs:
  - create
  - delete
  - get
  - list
  - watch
