apiVersion: iam.miloapis.com/v1alpha1
kind: ProtectedResource
metadata:
  name: connect.datumapis.com-connectoradvertisement
spec:
  serviceRef:
    name: connect-datumapis-com
  kind: ConnectorAdvertisement
  plural: connectoradvertisements
  singular: connectoradvertisement
  permissions:
  - list
  - get
  - create
  - update
  - patch
  - delete
  - watch
  - updateStatus
  parentResources:
  - apiGroup: resourcemanager.miloapis.com
    kind: Project
