[package]
name = "connect-ip-adapter"
version = "0.1.0"
edition = "2024"
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
ipnet = { version = "2", features = ["serde"] }
tokio = { workspace = true }
libc = "0.2"

[target.'cfg(windows)'.dependencies]
sha2 = "0.10"
wintun = "0.5.1"
windows-sys = { version = "0.52", features = [
    "Win32_Foundation",
    "Win32_NetworkManagement_IpHelper",
    "Win32_NetworkManagement_Ndis",
    "Win32_Networking_WinSock",
    "Win32_Security",
    "Win32_Storage_FileSystem",
] }
